/*
  File autogenerated by gengetopt version 2.20
  generated with the following command:
  gengetopt --file-name=cmdline --unamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Automating the creation of documentation for the design of printed circuit \nboards (Автоматизация создания документации конструктора печатных плат)";

const char *gengetopt_args_info_usage = "Usage: VP_auto [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "*******************************************************************************\n* 2018 Yuri Stepanenko stepanenkoyra@gmail.com                                *\n* License : GNU GENERAL PUBLIC LICENSE Version 3, June 2007                   *\n* For electronic designers from Russian Federation.                           *\n* From the report files E-CAD systems create textual documentation according  *\n* to ESKD (Из файлов отчетов E-CAD систем создаёт текстовую документацию      *\n* согласно ЕСКД)                                                              *\n* Details are given in VP_auto.pdf (Подробности доступны в VP_auto.pdf        *\n*******************************************************************************";

const char *gengetopt_args_info_help[] = {
  "  -h, --help               Print help and exit",
  "  -V, --version            Print version and exit",
  "  -f, --filename=STRING    do-file for analysis (do-файл для анализа)",
  "  -c, --copies=LONG        Number of copies of the product (Количество копий \n                             изделия)",
  "  -s, --per_style=STRING   List of elements (Стиль переченя элементов). Style :\n                             sch  - list of elements for the electrical circuit\n                               (перечень элементов для электрической схемы);\n                             doc  - for inclusion in instruction additions (для\n                               включения в дополнения инструкций).  (possible \n                             values=\"sch\", \"doc\" default=`sch')",
  "  -o, --out_folder=STRING  Folder for outputs. Default do-file_Dir/../out/ \n                             (Директория для выходных файлов. По умолчанию \n                             do-file_Dir/../out/)",
  "  -r, --res_folder=STRING  Path to resource files. Default VP_auto_Dir/res/ \n                             (Путь к файлам ресурсов. По умолчанию \n                             VP_auto_Dir/res/)",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

char *cmdline_parser_per_style_values[] = {"sch", "doc", 0} ;	/* Possible values for per_style.  */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->filename_given = 0 ;
  args_info->copies_given = 0 ;
  args_info->per_style_given = 0 ;
  args_info->out_folder_given = 0 ;
  args_info->res_folder_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->filename_arg = NULL;
  args_info->filename_orig = NULL;
  args_info->copies_orig = NULL;
  args_info->per_style_arg = gengetopt_strdup ("sch");
  args_info->per_style_orig = NULL;
  args_info->out_folder_arg = NULL;
  args_info->out_folder_orig = NULL;
  args_info->res_folder_arg = NULL;
  args_info->res_folder_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->filename_help = gengetopt_args_info_help[2] ;
  args_info->copies_help = gengetopt_args_info_help[3] ;
  args_info->per_style_help = gengetopt_args_info_help[4] ;
  args_info->out_folder_help = gengetopt_args_info_help[5] ;
  args_info->res_folder_help = gengetopt_args_info_help[6] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->filename_arg)
    {
      free (args_info->filename_arg); /* free previous argument */
      args_info->filename_arg = 0;
    }
  if (args_info->filename_orig)
    {
      free (args_info->filename_orig); /* free previous argument */
      args_info->filename_orig = 0;
    }
  if (args_info->copies_orig)
    {
      free (args_info->copies_orig); /* free previous argument */
      args_info->copies_orig = 0;
    }
  if (args_info->per_style_arg)
    {
      free (args_info->per_style_arg); /* free previous argument */
      args_info->per_style_arg = 0;
    }
  if (args_info->per_style_orig)
    {
      free (args_info->per_style_orig); /* free previous argument */
      args_info->per_style_orig = 0;
    }
  if (args_info->out_folder_arg)
    {
      free (args_info->out_folder_arg); /* free previous argument */
      args_info->out_folder_arg = 0;
    }
  if (args_info->out_folder_orig)
    {
      free (args_info->out_folder_orig); /* free previous argument */
      args_info->out_folder_orig = 0;
    }
  if (args_info->res_folder_arg)
    {
      free (args_info->res_folder_arg); /* free previous argument */
      args_info->res_folder_arg = 0;
    }
  if (args_info->res_folder_orig)
    {
      free (args_info->res_folder_orig); /* free previous argument */
      args_info->res_folder_orig = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->filename_given) {
    if (args_info->filename_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "filename", args_info->filename_orig);
    } else {
      fprintf(outfile, "%s\n", "filename");
    }
  }
  if (args_info->copies_given) {
    if (args_info->copies_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "copies", args_info->copies_orig);
    } else {
      fprintf(outfile, "%s\n", "copies");
    }
  }
  if (args_info->per_style_given) {
    if (args_info->per_style_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "per_style", args_info->per_style_orig);
    } else {
      fprintf(outfile, "%s\n", "per_style");
    }
  }
  if (args_info->out_folder_given) {
    if (args_info->out_folder_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "out_folder", args_info->out_folder_orig);
    } else {
      fprintf(outfile, "%s\n", "out_folder");
    }
  }
  if (args_info->res_folder_given) {
    if (args_info->res_folder_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "res_folder", args_info->res_folder_orig);
    } else {
      fprintf(outfile, "%s\n", "res_folder");
    }
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/*
 * Returns:
 * - the index of the matched value
 * - -1 if no argument has been specified
 * - -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values are matched */
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (! args_info->filename_given)
    {
      fprintf (stderr, "%s: '--filename' ('-f') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  
  /* checks for dependences among options */

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int found = 0;
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "filename",	1, NULL, 'f' },
        { "copies",	1, NULL, 'c' },
        { "per_style",	1, NULL, 's' },
        { "out_folder",	1, NULL, 'o' },
        { "res_folder",	1, NULL, 'r' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVf:c:s:o:r:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'f':	/* do-file for analysis (do-файл для анализа).  */
          if (local_args_info.filename_given)
            {
              fprintf (stderr, "%s: `--filename' (`-f') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->filename_given && ! override)
            continue;
          local_args_info.filename_given = 1;
          args_info->filename_given = 1;
          if (args_info->filename_arg)
            free (args_info->filename_arg); /* free previous string */
          args_info->filename_arg = gengetopt_strdup (optarg);
          if (args_info->filename_orig)
            free (args_info->filename_orig); /* free previous string */
          args_info->filename_orig = gengetopt_strdup (optarg);
          break;

        case 'c':	/* Number of copies of the product (Количество копий изделия).  */
          if (local_args_info.copies_given)
            {
              fprintf (stderr, "%s: `--copies' (`-c') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->copies_given && ! override)
            continue;
          local_args_info.copies_given = 1;
          args_info->copies_given = 1;
          args_info->copies_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->copies_orig)
            free (args_info->copies_orig); /* free previous string */
          args_info->copies_orig = gengetopt_strdup (optarg);
          break;

        case 's':	/* List of elements (Стиль переченя элементов). Style :
        sch  - list of elements for the electrical circuit
          (перечень элементов для электрической схемы);
        doc  - for inclusion in instruction additions (для
          включения в дополнения инструкций)..  */
          if (local_args_info.per_style_given)
            {
              fprintf (stderr, "%s: `--per_style' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if ((found = check_possible_values((optarg ? optarg : 0 ), cmdline_parser_per_style_values)) < 0)
            {
              fprintf (stderr, "%s: %s argument, \"%s\", for option `--per_style' (`-s')%s\n", argv[0], (found == -2) ? "ambiguous" : "invalid", optarg, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->per_style_given && ! override)
            continue;
          local_args_info.per_style_given = 1;
          args_info->per_style_given = 1;
          if (args_info->per_style_arg)
            free (args_info->per_style_arg); /* free previous string */
          args_info->per_style_arg = gengetopt_strdup (cmdline_parser_per_style_values[found]);
          if (args_info->per_style_orig)
            free (args_info->per_style_orig); /* free previous string */
          args_info->per_style_orig = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Folder for outputs. Default do-file_Dir/../out/ (Директория для выходных файлов. По умолчанию do-file_Dir/../out/).  */
          if (local_args_info.out_folder_given)
            {
              fprintf (stderr, "%s: `--out_folder' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->out_folder_given && ! override)
            continue;
          local_args_info.out_folder_given = 1;
          args_info->out_folder_given = 1;
          if (args_info->out_folder_arg)
            free (args_info->out_folder_arg); /* free previous string */
          args_info->out_folder_arg = gengetopt_strdup (optarg);
          if (args_info->out_folder_orig)
            free (args_info->out_folder_orig); /* free previous string */
          args_info->out_folder_orig = gengetopt_strdup (optarg);
          break;

        case 'r':	/* Path to resource files. Default VP_auto_Dir/res/ (Путь к файлам ресурсов. По умолчанию VP_auto_Dir/res/).  */
          if (local_args_info.res_folder_given)
            {
              fprintf (stderr, "%s: `--res_folder' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->res_folder_given && ! override)
            continue;
          local_args_info.res_folder_given = 1;
          args_info->res_folder_given = 1;
          if (args_info->res_folder_arg)
            free (args_info->res_folder_arg); /* free previous string */
          args_info->res_folder_arg = gengetopt_strdup (optarg);
          if (args_info->res_folder_orig)
            free (args_info->res_folder_orig); /* free previous string */
          args_info->res_folder_orig = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
